package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppSettings generated by hbm2java
 */
@Entity
@Table(name = "app_settings", catalog = "cloudlanes")
public class AppSettings implements java.io.Serializable {

	private int settingId;
	private String settingName;
	private String settingValue;

	public AppSettings() {
	}

	public AppSettings(int settingId) {
		this.settingId = settingId;
	}

	public AppSettings(int settingId, String settingName, String settingValue) {
		this.settingId = settingId;
		this.settingName = settingName;
		this.settingValue = settingValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "setting_id", unique = true, nullable = false)
	public int getSettingId() {
		return this.settingId;
	}

	public void setSettingId(int settingId) {
		this.settingId = settingId;
	}

	@Column(name = "setting_name", length = 45)
	public String getSettingName() {
		return this.settingName;
	}

	public void setSettingName(String settingName) {
		this.settingName = settingName;
	}

	@Column(name = "setting_value", length = 45)
	public String getSettingValue() {
		return this.settingValue;
	}

	public void setSettingValue(String settingValue) {
		this.settingValue = settingValue;
	}

}
