package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DriveModel generated by hbm2java
 */
@Entity
@Table(name = "drive_model", catalog = "cloudlanes")
public class DriveModel implements java.io.Serializable {

	private int modelId;
	private VtlBrand vtlBrand;
	private String modelName;
	
	public DriveModel() {
	}

	public DriveModel(int modelId) {
		this.modelId = modelId;
	}

	public DriveModel(int modelId, VtlBrand vtlBrand, String modelName) {
		this.modelId = modelId;
		this.vtlBrand = vtlBrand;
		this.modelName = modelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "model_id", unique = true, nullable = false)
	public int getModelId() {
		return this.modelId;
	}

	public void setModelId(int modelId) {
		this.modelId = modelId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vtl_brand_id")
	public VtlBrand getVtlBrand() {
		return this.vtlBrand;
	}

	public void setVtlBrand(VtlBrand vtlBrand) {
		this.vtlBrand = vtlBrand;
	}

	@Column(name = "model_name", length = 45)
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}
}
