package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DriveVendor generated by hbm2java
 */
@Entity
@Table(name = "drive_vendor", catalog = "cloudlanes")
public class DriveVendor implements java.io.Serializable {

	private int vendorId;
	private VtlBrand vtlBrand;
	private String vendorName;

	public DriveVendor() {
	}

	public DriveVendor(int vendorId) {
		this.vendorId = vendorId;
	}

	public DriveVendor(int vendorId, VtlBrand vtlBrand, String vendorName) {
		this.vendorId = vendorId;
		this.vtlBrand = vtlBrand;
		this.vendorName = vendorName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vendor_id", unique = true, nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vtl_brand_id")
	public VtlBrand getVtlBrand() {
		return this.vtlBrand;
	}

	public void setVtlBrand(VtlBrand vtlBrand) {
		this.vtlBrand = vtlBrand;
	}

	@Column(name = "vendor_name", length = 45)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
}
