package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "cloudlanes")
public class Job implements java.io.Serializable {

	private int jobId;
	private Vault vault;
	private Tape tape;
	private String jobName;
	private String type;
	private String status;
	private Long creationTs;
	private Long startTs;
	private Long completionTs;
	private String statusMessage;
	private Byte hasError;
	private Long percentComplete;

	public Job() {
	}

	public Job(int jobId) {
		this.jobId = jobId;
	}

	public Job(int jobId, Vault vault, Tape tape, String jobName, String type,
			String status, Long creationTs, Long startTs, Long completionTs,
			String statusMessage, Byte hasError, Long percentComplete) {
		this.jobId = jobId;
		this.vault = vault;
		this.tape = tape;
		this.jobName = jobName;
		this.type = type;
		this.status = status;
		this.creationTs = creationTs;
		this.startTs = startTs;
		this.completionTs = completionTs;
		this.statusMessage = statusMessage;
		this.hasError = hasError;
		this.percentComplete = percentComplete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_id", unique = true, nullable = false)
	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vault_id")
	public Vault getVault() {
		return this.vault;
	}

	public void setVault(Vault vault) {
		this.vault = vault;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tape_id")
	public Tape getTape() {
		return this.tape;
	}

	public void setTape(Tape tape) {
		this.tape = tape;
	}

	@Column(name = "job_name", length = 45)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "creation_ts")
	public Long getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Long creationTs) {
		this.creationTs = creationTs;
	}

	@Column(name = "start_ts")
	public Long getStartTs() {
		return this.startTs;
	}

	public void setStartTs(Long startTs) {
		this.startTs = startTs;
	}

	@Column(name = "completion_ts")
	public Long getCompletionTs() {
		return this.completionTs;
	}

	public void setCompletionTs(Long completionTs) {
		this.completionTs = completionTs;
	}

	@Column(name = "status_message", length = 45)
	public String getStatusMessage() {
		return this.statusMessage;
	}

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}

	@Column(name = "hasError")
	public Byte getHasError() {
		return this.hasError;
	}

	public void setHasError(Byte hasError) {
		this.hasError = hasError;
	}

	@Column(name = "percentComplete", precision = 10, scale = 0)
	public Long getPercentComplete() {
		return this.percentComplete;
	}

	public void setPercentComplete(Long percentComplete) {
		this.percentComplete = percentComplete;
	}

}
