package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MediaType generated by hbm2java
 */
@Entity
@Table(name = "media_type", catalog = "cloudlanes")
public class MediaType implements java.io.Serializable {

	private int typeId;
	private VtlBrand vtlBrand;
	private String typeName;
	private int rawCapacityMB;
	private String barcodePrefix;
	private String barcodeSuffix;

	public MediaType() {
	}

	public MediaType(int typeId) {
		this.typeId = typeId;
	}

	public MediaType(int typeId, VtlBrand vtlBrand, String typeName) {
		this.typeId = typeId;
		this.vtlBrand = vtlBrand;
		this.typeName = typeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "type_id", unique = true, nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vtl_brand_id")
	public VtlBrand getVtlBrand() {
		return this.vtlBrand;
	}

	public void setVtlBrand(VtlBrand vtlBrand) {
		this.vtlBrand = vtlBrand;
	}

	@Column(name = "type_name", length = 45)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "raw_capacity_mb")
	public int getRawCapacityMB() {
		return rawCapacityMB;
	}

	public void setRawCapacityMB(int rawCapacityMB) {
		this.rawCapacityMB = rawCapacityMB;
	}

	@Column(name = "barcode_prefix")
	public String getBarcodePrefix() {
		return barcodePrefix;
	}

	public void setBarcodePrefix(String barcodePrefix) {
		this.barcodePrefix = barcodePrefix;
	}

	@Column(name = "barcode_suffix")
	public String getBarcodeSuffix() {
		return barcodeSuffix;
	}

	public void setBarcodeSuffix(String barcodeSuffix) {
		this.barcodeSuffix = barcodeSuffix;
	}
}
