package com.cloudlanes.db.entities;

// Generated 25 Nov, 2015 4:11:55 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Policy generated by hbm2java
 */
@Entity
@Table(name = "policy", catalog = "cloudlanes")
@XmlRootElement
public class Policy implements java.io.Serializable {
	@XmlElement
	private int Id;
	@XmlElement
	private String name;
	@XmlElement
	private String type;
	@XmlElement
	private String criteria;
	@XmlElement
	private String value;

	public Policy() {
	}

	public Policy(int id, String name, String type, String criteria,
			String value) {
		super();
		Id = id;
		this.name = name;
		this.type = type;
		this.criteria = criteria;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "policy_id", unique = true, nullable = false)
	public int getId() {
		return this.Id;
	}

	public void setId(int policyId) {
		this.Id = policyId;
	}

	@Column(name = "policy_name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String policyName) {
		this.name = policyName;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "policy_key", length = 45)
	public String getCriteria() {
		return criteria;
	}

	public void setCriteria(String criteria) {
		this.criteria = criteria;
	}


	@Column(name = "policy_value", length = 45)
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
