package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Slot generated by hbm2java
 */
@Entity
@Table(name = "slot", catalog = "cloudlanes")
public class Slot implements java.io.Serializable {

	private int slotId;
	private Vtl vtl;
	private String slotName;
	private Byte isEmpty;
	private Set<Tape> tapes = new HashSet<Tape>(0);

	public Slot() {
	}

	public Slot(int slotId) {
		this.slotId = slotId;
	}

	public Slot(int slotId, Vtl vtl, String slotName, Byte isEmpty, Set<Tape> tapes) {
		this.slotId = slotId;
		this.vtl = vtl;
		this.slotName = slotName;
		this.isEmpty = isEmpty;
		this.tapes = tapes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "slot_id", unique = true, nullable = false)
	public int getSlotId() {
		return this.slotId;
	}

	public void setSlotId(int slotId) {
		this.slotId = slotId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vtl_id")
	public Vtl getVtl() {
		return this.vtl;
	}

	public void setVtl(Vtl vtl) {
		this.vtl = vtl;
	}

	@Column(name = "slot_name", length = 50)
	public String getSlotName() {
		return this.slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}

	@Column(name = "is_empty")
	public Byte getIsEmpty() {
		return this.isEmpty;
	}

	public void setIsEmpty(Byte isEmpty) {
		this.isEmpty = isEmpty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slot")
	public Set<Tape> getTapes() {
		return this.tapes;
	}

	public void setTapes(Set<Tape> tapes) {
		this.tapes = tapes;
	}

}
