package com.cloudlanes.db.entities;


// default package
// Generated 25 Nov, 2015 4:11:55 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "cloudlanes")
@XmlRootElement
public class User implements java.io.Serializable {
	@XmlElement
	private String user_id;
	@XmlElement
	private String password;
	@XmlElement
	private Role role;

	public User() {
	}

	public User(String userId) {
		this.setUser_id(userId);
	}

	public User(String userId, Role role, String password) {
		this.setUser_id(userId);
		this.role = role;
		this.password = password;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}
	@ManyToOne(fetch = FetchType.LAZY )
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}


	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}



}
