package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0



import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Vault generated by hbm2java
 */
@Entity
@Table(name = "vault", catalog = "cloudlanes")
@XmlRootElement
public class Vault implements java.io.Serializable {
	@XmlElement
	private Integer vaultId;
	@XmlElement
	private String accountName;
	@XmlElement
	private String type;
	@XmlElement
	private String accessKey;
	@XmlElement
	private String secretKey;
	@XmlElement
	private String container;

	public Vault() {
	}

	public Vault(String accountName, String type
			, String accessKey, String secretKey,
			String container, Set<Vtl> vtls, Set<Job> jobs) {
		this.type = type;
		this.accountName = accountName;
		this.accessKey = accessKey;
		this.secretKey = secretKey;
		this.container=container;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "vault_id", unique = true, nullable = false)
	public Integer getVaultId() {
		return this.vaultId;
	}

	public void setVaultId(Integer vaultId) {
		this.vaultId = vaultId;
	}



	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "account_name", length = 45)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "access_key", length = 45)
	public String getAccessKey() {
		return this.accessKey;
	}

	public void setAccessKey(String accessKey) {
		this.accessKey = accessKey;
	}

	@Column(name = "secret_key", length = 45)
	public String getSecretKey() {
		return this.secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	@Column(name = "container", length = 45)
	public String getContainer() {
		return this.container;
	}

	public void setContainer(String bucketId) {
		this.container = bucketId;
	}


}
