package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vtl generated by hbm2java
 */
@Entity
@Table(name = "vtl", catalog = "cloudlanes")
public class Vtl implements java.io.Serializable {

	private Integer vtlId;
	private Vault vault;
	private VtlModel vtlModel;
	private VtlBrand vtlBrand;
	private String vtlName;
	private Integer slotCount;
	private Integer iePortCount;
	private Integer driveCount;
	private Byte compressionEnabled;
	private Integer emptySlotCount;
	private Integer pickerCount;
	private Integer compressionFactor;
	private String scsiDevFilePath;
	private int vtlLibId;
	
	
	private Set<Slot> slots = new HashSet<Slot>(0);
	private Set<Tape> tapes = new HashSet<Tape>(0);
	private Set<Drive> drives = new HashSet<Drive>(0);

	public Vtl() {
	}

	public Vtl(Vault vault, VtlModel vtlModel, VtlBrand vtlBrand,
			String vtlName, Integer slotCount, Integer iePortCount,
			Integer driveCount, Byte isCompressed, Integer emptySlotCount,
			Set<Slot> slots, Set<Tape> tapes, Set<Drive> drives, int pickerCount, int compressionFactor, String devFilePath) {
		this.vault = vault;
		this.vtlModel = vtlModel;
		this.vtlBrand = vtlBrand;
		this.vtlName = vtlName;
		this.slotCount = slotCount;
		this.iePortCount = iePortCount;
		this.driveCount = driveCount;
		this.compressionEnabled = isCompressed;
		this.emptySlotCount = emptySlotCount;
		this.slots = slots;
		this.tapes = tapes;
		this.drives = drives;
		this.pickerCount = pickerCount;
		this.compressionFactor = compressionFactor;
		this.scsiDevFilePath = devFilePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vtl_id", unique = true, nullable = false)
	public Integer getVtlId() {
		return this.vtlId;
	}

	public void setVtlId(Integer vtlId) {
		this.vtlId = vtlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vault_id")
	public Vault getVault() {
		return this.vault;
	}

	public void setVault(Vault vault) {
		this.vault = vault;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vtl_model_id")
	public VtlModel getVtlModel() {
		return this.vtlModel;
	}

	public void setVtlModel(VtlModel vtlModel) {
		this.vtlModel = vtlModel;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "vtl_brand_id")
	public VtlBrand getVtlBrand() {
		return this.vtlBrand;
	}

	public void setVtlBrand(VtlBrand vtlBrand) {
		this.vtlBrand = vtlBrand;
	}

	@Column(name = "vtl_name", length = 50)
	public String getVtlName() {
		return this.vtlName;
	}

	public void setVtlName(String vtlName) {
		this.vtlName = vtlName;
	}

	@Column(name = "slot_count")
	public Integer getSlotCount() {
		return this.slotCount;
	}

	public void setSlotCount(Integer slotCount) {
		this.slotCount = slotCount;
	}

	@Column(name = "ie_port_count")
	public Integer getIePortCount() {
		return this.iePortCount;
	}

	public void setIePortCount(Integer iePortCount) {
		this.iePortCount = iePortCount;
	}

	@Column(name = "drive_count")
	public Integer getDriveCount() {
		return this.driveCount;
	}

	public void setDriveCount(Integer driveCount) {
		this.driveCount = driveCount;
	}

	@Column(name = "compression_enabled")
	public Byte getCompressionEnabled() {
		return this.compressionEnabled;
	}

	public void setCompressionEnabled(Byte isCompressed) {
		this.compressionEnabled = isCompressed;
	}

	@Column(name = "empty_slot_count")
	public Integer getEmptySlotCount() {
		return this.emptySlotCount;
	}

	public void setEmptySlotCount(Integer emptySlotCount) {
		this.emptySlotCount = emptySlotCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vtl", cascade = CascadeType.ALL)
	public Set<Slot> getSlots() {
		return this.slots;
	}

	public void setSlots(Set<Slot> slots) {
		this.slots = slots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vtl", cascade = CascadeType.ALL)
	public Set<Tape> getTapes() {
		return this.tapes;
	}

	public void setTapes(Set<Tape> tapes) {
		this.tapes = tapes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vtl", cascade = CascadeType.ALL)
	public Set<Drive> getDrives() {
		return this.drives;
	}

	public void setDrives(Set<Drive> drives) {
		this.drives = drives;
	}

	@Column(name = "picker_count")
	public Integer getPickerCount() {
		return pickerCount;
	}

	public void setPickerCount(Integer pickerCount) {
		this.pickerCount = pickerCount;
	}

	@Column(name = "compression_factor")
	public Integer getCompressionFactor() {
		return compressionFactor;
	}

	public void setCompressionFactor(Integer compressionFactor) {
		this.compressionFactor = compressionFactor;
	}

	@Column(name = "scsi_dev_file_path")
	public String getScsiDevFilePath() {
		return scsiDevFilePath;
	}

	public void setScsiDevFilePath(String scsiDevFilePath) {
		this.scsiDevFilePath = scsiDevFilePath;
	}

	@Column(name = "vtl_lib_id")
	public int getVtlLibId() {
		return vtlLibId;
	}

	public void setVtlLibId(int vtlLibId) {
		this.vtlLibId = vtlLibId;
	}

	
}
