package com.cloudlanes.db.entities;
// default package
// Generated 4 Dec, 2015 5:58:08 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VtlBrand generated by hbm2java
 */
@Entity
@Table(name = "vtl_brand", catalog = "cloudlanes")
public class VtlBrand implements java.io.Serializable {

	private int brandId;
	private String brandName;
	
	public VtlBrand() {
	}

	public VtlBrand(int brandId) {
		this.brandId = brandId;
	}

	public VtlBrand(int brandId, String brandName) {
		this.brandId = brandId;
		this.brandName = brandName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "brand_id", unique = true, nullable = false)
	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	@Column(name = "brand_name", length = 45)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}
}
